name: get stock price

on:
  schedule:
    # 對應台灣時間週一至週五 09:00 - 14:00 (UTC 01:00 - 06:00)
    - cron: "*/5 1-6 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run Python script
        run: python test1.py
